<a href="https://colab.research.google.com/github/diyorphpDev/week3-lab/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [35]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [33]:
# TODO: Create a vector tensor
vector = torch.tensor([[1, 2, 3, 4]])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([[1, 2, 3, 4]])
Number of dimensions: 2
Shape: torch.Size([1, 4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [32]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1,2,3],
                       [4,5,6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [31]:
# TODO: Create a 3D tensor
tensor_3d = torch.tensor([[[1, 2],
                        [3, 4],],

                        [[5, 6],
                        [7, 8],]])

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [26]:
# TODO: Create random tensor
random_tensor = torch.rand(size=(4,4))

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.8845, 0.2180, 0.4118, 0.0423],
        [0.3307, 0.8011, 0.3295, 0.4655],
        [0.8009, 0.2047, 0.1313, 0.4983],
        [0.6171, 0.5501, 0.4775, 0.1155]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [38]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(size=(3, 224, 224))

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [42]:
# TODO: Create zeros tensor
zeros = torch.zeros(size=(5,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [48]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones_like(random_tensor)

ones_like

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [50]:
# TODO: Create range tensor
range_tensor = torch.range(0, 20)
zero_to_twenty = torch.arange(start=0, end=20, step=2)
zero_to_twenty

/tmp/ipython-input-2995357445.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor = torch.range(0, 20)


tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [62]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.int64)
print(float16_tensor,float16_tensor.dtype)
print(int64_tensor,int64_tensor.dtype)


tensor([1., 2., 3.], dtype=torch.float16) torch.float16
tensor([1, 2, 3]) torch.int64


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [61]:
# TODO: Change dtype
float32_tensor = float16_tensor.type(torch.float32)
float32_tensor.dtype

torch.float32

## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [64]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2, 3, 4)
print(f"Shape of tensor: {info_tensor.shape}")
print(f"Datatype of tensor: {info_tensor.dtype}")
print(f"Device tensor is stored on: {info_tensor.device}")

Shape of tensor: torch.Size([2, 3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [67]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
addition = tensor + 5

# TODO: Subtract 10
subtraction = tensor - 10

# TODO: Multiply by 2
multiplication = tensor * 2

# TODO: Divide by 10
division = tensor / 10

print(addition)
print(subtraction)
print(multiplication)
print(division)


tensor([15, 25, 35])
tensor([ 0, 10, 20])
tensor([20, 40, 60])
tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [69]:
# TODO: Create A and B
A = torch.randn(2, 3)
B = torch.randn(3, 2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A,B)

# TODO: Matrix mul using @
result_at = A @ B

print(A)
print(B)
print("torch.mm: ", result_mm)
print("A @ B: ", result_at)

tensor([[ 1.3477, -1.6177,  0.2080],
        [-1.5381,  2.8156,  1.3028]])
tensor([[ 0.0704, -0.2218],
        [-0.9802,  0.0498],
        [-0.4573,  0.0787]])
torch.mm:  tensor([[ 1.5853, -0.3631],
        [-3.4638,  0.5839]])
A @ B:  tensor([[ 1.5853, -0.3631],
        [-3.4638,  0.5839]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [72]:


agg_tensor = torch.arange(0, 101)

min_val = agg_tensor.min()

max_val = agg_tensor.max()

mean_val = agg_tensor.type(torch.float32).mean()

sum_val = agg_tensor.sum()

print(f"Min: {min_val}")
print(f"Max: {max_val}")
print(f"Mean: {mean_val}")
print(f"Sum: {sum_val}")


Min: 0
Max: 100
Mean: 50.0
Sum: 5050


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [74]:

agg_tensor = torch.arange(0, 101)
# TODO: Argmin
arg_min = agg_tensor.argmin()
# TODO: Argmax
arg_max = agg_tensor.argmax()

print(f"min: {arg_min}")
print(f"Max: {arg_max}")

min: 0
Max: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [77]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2, 5)
print(reshape_tensor.shape)
print(f"reshaped: {reshaped.shape}")
print(f"tensor:\n{reshaped}")

torch.Size([10])
reshaped: torch.Size([2, 5])
tensor:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [78]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
stacked_vert = torch.stack([tensor1, tensor2], dim=0)
# TODO: Stack horizontally (dim=1)
stacked_horiz = torch.stack([tensor1, tensor2], dim=1)
print(stacked_vert)
print(stacked_horiz)


tensor([[[0.4361, 0.2632],
         [0.9854, 0.1322]],

        [[0.5387, 0.5060],
         [0.8901, 0.1065]]])
tensor([[[0.4361, 0.2632],
         [0.5387, 0.5060]],

        [[0.9854, 0.1322],
         [0.8901, 0.1065]]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [79]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = squeeze_tensor.squeeze()

# TODO: Unsqueeze on dim=0
unsqueezed = squeeze_tensor.unsqueeze(dim=0)
print(squeezed)
print(unsqueezed)

tensor([0.4370, 0.6543, 0.8952])
tensor([[[[0.4370],
          [0.6543],
          [0.8952]]]])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [81]:
import torch

image_tensor = torch.rand(3, 100, 100)
permuted = image_tensor.permute(1, 2, 0)
print(permuted.shape)


torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [82]:


index_tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

# TODO: Get 5
five = index_tensor[0, 1, 1]
print(five)

# TODO: Get second row [4, 5, 6]
second_row = index_tensor[0, 1, :]
print(second_row)


tensor(5)
tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [84]:


numpy_array = np.array([1, 2, 3, 4])

from_numpy = torch.from_numpy(numpy_array)

print(f"NumPy array: {numpy_array}")
print(f"PyTorch tensor: {from_numpy}")


NumPy array: [1 2 3 4]
PyTorch tensor: tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [85]:

pytorch_tensor = torch.tensor([5, 6, 7, 8])

# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()

print(f"PyTorch tensor: {pytorch_tensor}")
print(f"NumPy array: {to_numpy}")


PyTorch tensor: tensor([5, 6, 7, 8])
NumPy array: [5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [86]:
import torch

# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2, 2)

# TODO: Reset seed for second tensor
torch.manual_seed(77)
rand2 = torch.rand(2, 2)

print(rand1 == rand2)


tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [87]:
import torch

# TODO: Set device
device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)

test_tensor = torch.tensor([1, 2, 3], device=device)
print(test_tensor.device)


cpu
cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [89]:
import torch
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

gpu_tensor = torch.tensor([10, 20, 30])

gpu_tensor = gpu_tensor.to(device)
print(gpu_tensor.device)

# TODO: Move to device
cpu_numpy = gpu_tensor.cpu().numpy()

print(cpu_numpy)
print(type(cpu_numpy))


cpu
[10 20 30]
<class 'numpy.ndarray'>
